<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        if (DB::table('patients')->count() > 0) {
            $this->command->info('Patients already seeded, skipping.');
            return;
        }

        $patients = [
            ['first_name' => 'Juan',         'last_name' => 'Santos',       'date_of_birth' => '1945-03-12', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Purok 4, Bulua, Cagayan de Oro',            'phone_number' => '09171000001', 'date_registered' => '2025-01-05'],
            ['first_name' => 'Maria',        'last_name' => 'Reyes',        'date_of_birth' => '1938-07-24', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Purok 2, Lapasan, Cagayan de Oro',          'phone_number' => '09181000002', 'date_registered' => '2025-01-07'],
            ['first_name' => 'Pedro',        'last_name' => 'Garcia',       'date_of_birth' => '1950-11-03', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Barangay 4, Cagayan de Oro',                'phone_number' => '09191000003', 'date_registered' => '2025-01-10'],
            ['first_name' => 'Rosario',      'last_name' => 'Dela Cruz',    'date_of_birth' => '1942-05-18', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Gusa, Cagayan de Oro',                      'phone_number' => '09201000004', 'date_registered' => '2025-01-12'],
            ['first_name' => 'Eduardo',      'last_name' => 'Flores',       'date_of_birth' => '1955-09-30', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Nazareth, Cagayan de Oro',                  'phone_number' => '09211000005', 'date_registered' => '2025-01-15'],
            ['first_name' => 'Consolacion',  'last_name' => 'Bautista',     'date_of_birth' => '1948-02-14', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Camaman-an, Cagayan de Oro',                'phone_number' => '09221000006', 'date_registered' => '2025-01-18'],
            ['first_name' => 'Amado',        'last_name' => 'Villanueva',   'date_of_birth' => '1952-06-07', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Carmen, Cagayan de Oro',                    'phone_number' => '09231000007', 'date_registered' => '2025-01-20'],
            ['first_name' => 'Leonora',      'last_name' => 'Cruz',         'date_of_birth' => '1939-12-22', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Macabalan, Cagayan de Oro',                 'phone_number' => '09241000008', 'date_registered' => '2025-01-22'],
            ['first_name' => 'Bernardo',     'last_name' => 'Torres',       'date_of_birth' => '1946-08-16', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Cugman, Cagayan de Oro',                    'phone_number' => '09251000009', 'date_registered' => '2025-01-25'],
            ['first_name' => 'Remedios',     'last_name' => 'Gonzales',     'date_of_birth' => '1943-04-09', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Balulang, Cagayan de Oro',                  'phone_number' => '09261000010', 'date_registered' => '2025-01-28'],
            ['first_name' => 'Alfredo',      'last_name' => 'Mendoza',      'date_of_birth' => '1957-01-27', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Iponan, Cagayan de Oro',                    'phone_number' => '09271000011', 'date_registered' => '2025-02-01'],
            ['first_name' => 'Teresita',     'last_name' => 'Ramos',        'date_of_birth' => '1940-10-05', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Agusan, Cagayan de Oro',                    'phone_number' => '09281000012', 'date_registered' => '2025-02-03'],
            ['first_name' => 'Victorino',    'last_name' => 'Diaz',         'date_of_birth' => '1953-07-14', 'sex' => 'M', 'marital_status' => 'Separated', 'address' => 'Consolacion, Cagayan de Oro',               'phone_number' => '09291000013', 'date_registered' => '2025-02-05'],
            ['first_name' => 'Erlinda',      'last_name' => 'Morales',      'date_of_birth' => '1947-03-28', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Puerto, Cagayan de Oro',                    'phone_number' => '09301000014', 'date_registered' => '2025-02-08'],
            ['first_name' => 'Celestino',    'last_name' => 'Aquino',       'date_of_birth' => '1960-11-19', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Kauswagan, Cagayan de Oro',                 'phone_number' => '09171000015', 'date_registered' => '2025-02-10'],
            ['first_name' => 'Natividad',    'last_name' => 'Reyes',        'date_of_birth' => '1936-06-02', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Barangay 17, Cagayan de Oro',               'phone_number' => '09181000016', 'date_registered' => '2025-02-12'],
            ['first_name' => 'Gregorio',     'last_name' => 'Buenaventura', 'date_of_birth' => '1949-09-11', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Lapasan, Cagayan de Oro',                   'phone_number' => '09191000017', 'date_registered' => '2025-02-15'],
            ['first_name' => 'Esperanza',    'last_name' => 'Salazar',      'date_of_birth' => '1944-01-30', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Bulua, Cagayan de Oro',                     'phone_number' => '09201000018', 'date_registered' => '2025-02-18'],
            ['first_name' => 'Rodrigo',      'last_name' => 'Pascual',      'date_of_birth' => '1958-05-23', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Gusa, Cagayan de Oro',                      'phone_number' => '09211000019', 'date_registered' => '2025-02-20'],
            ['first_name' => 'Felicidad',    'last_name' => 'Navarro',      'date_of_birth' => '1941-08-07', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Nazareth, Cagayan de Oro',                  'phone_number' => '09221000020', 'date_registered' => '2025-02-22'],
            ['first_name' => 'Aurelio',      'last_name' => 'Padilla',      'date_of_birth' => '1954-04-15', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Camaman-an, Cagayan de Oro',                'phone_number' => '09231000021', 'date_registered' => '2025-03-01'],
            ['first_name' => 'Carmelita',    'last_name' => 'Castillo',     'date_of_birth' => '1937-12-28', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Carmen, Cagayan de Oro',                    'phone_number' => '09241000022', 'date_registered' => '2025-03-03'],
            ['first_name' => 'Domingo',      'last_name' => 'Soriano',      'date_of_birth' => '1962-07-04', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Barangay 9, Cagayan de Oro',                'phone_number' => '09251000023', 'date_registered' => '2025-03-05'],
            ['first_name' => 'Visitacion',   'last_name' => 'Marcelo',      'date_of_birth' => '1945-02-17', 'sex' => 'F', 'marital_status' => 'Separated', 'address' => 'Macabalan, Cagayan de Oro',                 'phone_number' => '09261000024', 'date_registered' => '2025-03-08'],
            ['first_name' => 'Proceso',      'last_name' => 'Guerrero',     'date_of_birth' => '1951-10-08', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Indahag, Cagayan de Oro',                   'phone_number' => '09271000025', 'date_registered' => '2025-03-10'],
            ['first_name' => 'Eduvigis',     'last_name' => 'Aguilar',      'date_of_birth' => '1939-06-20', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Cugman, Cagayan de Oro',                    'phone_number' => '09281000026', 'date_registered' => '2025-03-12'],
            ['first_name' => 'Lucio',        'last_name' => 'Miranda',      'date_of_birth' => '1956-03-14', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Balulang, Cagayan de Oro',                  'phone_number' => '09291000027', 'date_registered' => '2025-03-15'],
            ['first_name' => 'Adoracion',    'last_name' => 'Medina',       'date_of_birth' => '1943-11-26', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Iponan, Cagayan de Oro',                    'phone_number' => '09301000028', 'date_registered' => '2025-03-18'],
            ['first_name' => 'Simeon',       'last_name' => 'Vargas',       'date_of_birth' => '1948-08-03', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Agusan, Cagayan de Oro',                    'phone_number' => '09171000029', 'date_registered' => '2025-03-20'],
            ['first_name' => 'Purificacion', 'last_name' => 'Ibarra',       'date_of_birth' => '1935-04-09', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Consolacion, Cagayan de Oro',               'phone_number' => '09181000030', 'date_registered' => '2025-03-22'],
            ['first_name' => 'Iluminado',    'last_name' => 'Delos Santos', 'date_of_birth' => '1964-01-18', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Puerto, Cagayan de Oro',                    'phone_number' => '09191000031', 'date_registered' => '2025-04-01'],
            ['first_name' => 'Angelita',     'last_name' => 'Ocampo',       'date_of_birth' => '1946-09-05', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Kauswagan, Cagayan de Oro',                 'phone_number' => '09201000032', 'date_registered' => '2025-04-03'],
            ['first_name' => 'Ruperto',      'last_name' => 'Reyes',        'date_of_birth' => '1953-05-29', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Barangay 22, Cagayan de Oro',               'phone_number' => '09211000033', 'date_registered' => '2025-04-05'],
            ['first_name' => 'Dolores',      'last_name' => 'Abad',         'date_of_birth' => '1940-02-11', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Lapasan, Cagayan de Oro',                   'phone_number' => '09221000034', 'date_registered' => '2025-04-08'],
            ['first_name' => 'Saturnino',    'last_name' => 'Jimenez',      'date_of_birth' => '1959-12-24', 'sex' => 'M', 'marital_status' => 'Separated', 'address' => 'Gusa, Cagayan de Oro',                      'phone_number' => '09231000035', 'date_registered' => '2025-04-10'],
            ['first_name' => 'Soledad',      'last_name' => 'Cabrera',      'date_of_birth' => '1942-07-16', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Nazareth, Cagayan de Oro',                  'phone_number' => '09241000036', 'date_registered' => '2025-04-12'],
            ['first_name' => 'Maximo',       'last_name' => 'Pineda',       'date_of_birth' => '1950-03-07', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Camaman-an, Cagayan de Oro',                'phone_number' => '09251000037', 'date_registered' => '2025-04-15'],
            ['first_name' => 'Candelaria',   'last_name' => 'Alvarez',      'date_of_birth' => '1936-10-20', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Carmen, Cagayan de Oro',                    'phone_number' => '09261000038', 'date_registered' => '2025-04-18'],
            ['first_name' => 'Florentino',   'last_name' => 'Guevarra',     'date_of_birth' => '1957-06-13', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Macabalan, Cagayan de Oro',                 'phone_number' => '09271000039', 'date_registered' => '2025-04-20'],
            ['first_name' => 'Resurreccion', 'last_name' => 'Lim',          'date_of_birth' => '1944-01-25', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Indahag, Cagayan de Oro',                   'phone_number' => '09281000040', 'date_registered' => '2025-04-22'],
            ['first_name' => 'Hermogenes',   'last_name' => 'Dela Torre',   'date_of_birth' => '1963-09-08', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Cugman, Cagayan de Oro',                    'phone_number' => '09291000041', 'date_registered' => '2025-05-01'],
            ['first_name' => 'Magdalena',    'last_name' => 'Reyes',        'date_of_birth' => '1938-05-21', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Balulang, Cagayan de Oro',                  'phone_number' => '09301000042', 'date_registered' => '2025-05-03'],
            ['first_name' => 'Timoteo',      'last_name' => 'Santiago',     'date_of_birth' => '1952-02-14', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Iponan, Cagayan de Oro',                    'phone_number' => '09171000043', 'date_registered' => '2025-05-05'],
            ['first_name' => 'Corazon',      'last_name' => 'Fernandez',    'date_of_birth' => '1947-11-27', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Agusan, Cagayan de Oro',                    'phone_number' => '09181000044', 'date_registered' => '2025-05-08'],
            ['first_name' => 'Bartolome',    'last_name' => 'Herrera',      'date_of_birth' => '1955-08-10', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Consolacion, Cagayan de Oro',               'phone_number' => '09191000045', 'date_registered' => '2025-05-10'],
            ['first_name' => 'Presentacion', 'last_name' => 'Dela Rosa',    'date_of_birth' => '1941-04-03', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Puerto, Cagayan de Oro',                    'phone_number' => '09201000046', 'date_registered' => '2025-05-12'],
            ['first_name' => 'Crisostomo',   'last_name' => 'Bondoc',       'date_of_birth' => '1961-12-16', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Kauswagan, Cagayan de Oro',                 'phone_number' => '09211000047', 'date_registered' => '2025-05-15'],
            ['first_name' => 'Epifania',     'last_name' => 'Manalo',       'date_of_birth' => '1943-07-29', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Barangay 34, Cagayan de Oro',               'phone_number' => '09221000048', 'date_registered' => '2025-05-18'],
            ['first_name' => 'Exequiel',     'last_name' => 'Perez',        'date_of_birth' => '1948-03-22', 'sex' => 'M', 'marital_status' => 'Separated', 'address' => 'Lapasan, Cagayan de Oro',                   'phone_number' => '09231000049', 'date_registered' => '2025-05-20'],
            ['first_name' => 'Milagros',     'last_name' => 'Sarmiento',    'date_of_birth' => '1935-10-15', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Gusa, Cagayan de Oro',                      'phone_number' => '09241000050', 'date_registered' => '2025-05-22'],
            ['first_name' => 'Esteban',      'last_name' => 'Velasco',      'date_of_birth' => '1966-06-08', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Nazareth, Cagayan de Oro',                  'phone_number' => '09251000051', 'date_registered' => '2025-06-01'],
            ['first_name' => 'Rufina',       'last_name' => 'Belen',        'date_of_birth' => '1940-02-21', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Camaman-an, Cagayan de Oro',                'phone_number' => '09261000052', 'date_registered' => '2025-06-03'],
            ['first_name' => 'Meliton',      'last_name' => 'Corpus',       'date_of_birth' => '1954-11-04', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Carmen, Cagayan de Oro',                    'phone_number' => '09271000053', 'date_registered' => '2025-06-05'],
            ['first_name' => 'Imelda',       'last_name' => 'Enriquez',     'date_of_birth' => '1946-08-17', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Macabalan, Cagayan de Oro',                 'phone_number' => '09281000054', 'date_registered' => '2025-06-08'],
            ['first_name' => 'Demetrio',     'last_name' => 'Gutierrez',    'date_of_birth' => '1960-04-30', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Indahag, Cagayan de Oro',                   'phone_number' => '09291000055', 'date_registered' => '2025-06-10'],
            ['first_name' => 'Primitiva',    'last_name' => 'Lacson',       'date_of_birth' => '1937-01-13', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Cugman, Cagayan de Oro',                    'phone_number' => '09301000056', 'date_registered' => '2025-06-12'],
            ['first_name' => 'Abundio',      'last_name' => 'Mateo',        'date_of_birth' => '1949-09-26', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Balulang, Cagayan de Oro',                  'phone_number' => '09171000057', 'date_registered' => '2025-06-15'],
            ['first_name' => 'Consuelo',     'last_name' => 'Natividad',    'date_of_birth' => '1944-06-09', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Iponan, Cagayan de Oro',                    'phone_number' => '09181000058', 'date_registered' => '2025-06-18'],
            ['first_name' => 'Juanito',      'last_name' => 'Oblena',       'date_of_birth' => '1958-02-22', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Agusan, Cagayan de Oro',                    'phone_number' => '09191000059', 'date_registered' => '2025-06-20'],
            ['first_name' => 'Felipa',       'last_name' => 'Patriarca',    'date_of_birth' => '1941-11-05', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Consolacion, Cagayan de Oro',               'phone_number' => '09201000060', 'date_registered' => '2025-06-22'],
            ['first_name' => 'Arsenio',      'last_name' => 'Quiambao',     'date_of_birth' => '1953-07-18', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Puerto, Cagayan de Oro',                    'phone_number' => '09211000061', 'date_registered' => '2025-07-01'],
            ['first_name' => 'Norberta',     'last_name' => 'Robredo',      'date_of_birth' => '1939-04-01', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Kauswagan, Cagayan de Oro',                 'phone_number' => '09221000062', 'date_registered' => '2025-07-03'],
            ['first_name' => 'Glicerio',     'last_name' => 'Soriano',      'date_of_birth' => '1965-01-14', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Barangay 40, Cagayan de Oro',               'phone_number' => '09231000063', 'date_registered' => '2025-07-05'],
            ['first_name' => 'Asuncion',     'last_name' => 'Tadena',       'date_of_birth' => '1942-10-27', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Lapasan, Cagayan de Oro',                   'phone_number' => '09241000064', 'date_registered' => '2025-07-08'],
            ['first_name' => 'Macario',      'last_name' => 'Umali',        'date_of_birth' => '1956-07-10', 'sex' => 'M', 'marital_status' => 'Separated', 'address' => 'Gusa, Cagayan de Oro',                      'phone_number' => '09251000065', 'date_registered' => '2025-07-10'],
            ['first_name' => 'Visitacion',   'last_name' => 'Valencia',     'date_of_birth' => '1943-03-23', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Nazareth, Cagayan de Oro',                  'phone_number' => '09261000066', 'date_registered' => '2025-07-12'],
            ['first_name' => 'Wenceslao',    'last_name' => 'Yap',          'date_of_birth' => '1951-12-06', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Camaman-an, Cagayan de Oro',                'phone_number' => '09271000067', 'date_registered' => '2025-07-15'],
            ['first_name' => 'Zenaida',      'last_name' => 'Zamora',       'date_of_birth' => '1938-08-19', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Carmen, Cagayan de Oro',                    'phone_number' => '09281000068', 'date_registered' => '2025-07-18'],
            ['first_name' => 'Patricio',     'last_name' => 'Abrenica',     'date_of_birth' => '1960-05-02', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Macabalan, Cagayan de Oro',                 'phone_number' => '09291000069', 'date_registered' => '2025-07-20'],
            ['first_name' => 'Lilia',        'last_name' => 'Balois',       'date_of_birth' => '1947-01-15', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Indahag, Cagayan de Oro',                   'phone_number' => '09301000070', 'date_registered' => '2025-07-22'],
            ['first_name' => 'Victorino',    'last_name' => 'Cadiz',        'date_of_birth' => '1955-10-28', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Cugman, Cagayan de Oro',                    'phone_number' => '09171000071', 'date_registered' => '2025-08-01'],
            ['first_name' => 'Encarnacion',  'last_name' => 'Daza',         'date_of_birth' => '1940-07-11', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Balulang, Cagayan de Oro',                  'phone_number' => '09181000072', 'date_registered' => '2025-08-03'],
            ['first_name' => 'Marciano',     'last_name' => 'Espino',       'date_of_birth' => '1963-03-24', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Iponan, Cagayan de Oro',                    'phone_number' => '09191000073', 'date_registered' => '2025-08-05'],
            ['first_name' => 'Juana',        'last_name' => 'Feria',        'date_of_birth' => '1944-12-07', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Agusan, Cagayan de Oro',                    'phone_number' => '09201000074', 'date_registered' => '2025-08-08'],
            ['first_name' => 'Rosendo',      'last_name' => 'Gatmaitan',    'date_of_birth' => '1958-08-20', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Consolacion, Cagayan de Oro',               'phone_number' => '09211000075', 'date_registered' => '2025-08-10'],
            ['first_name' => 'Severina',     'last_name' => 'Hilario',      'date_of_birth' => '1936-05-03', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Puerto, Cagayan de Oro',                    'phone_number' => '09221000076', 'date_registered' => '2025-08-12'],
            ['first_name' => 'Gaudencio',    'last_name' => 'Imperial',     'date_of_birth' => '1950-01-16', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Kauswagan, Cagayan de Oro',                 'phone_number' => '09231000077', 'date_registered' => '2025-08-15'],
            ['first_name' => 'Florencia',    'last_name' => 'Javier',       'date_of_birth' => '1945-10-29', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Barangay 12, Cagayan de Oro',               'phone_number' => '09241000078', 'date_registered' => '2025-08-18'],
            ['first_name' => 'Renato',       'last_name' => 'Kimpo',        'date_of_birth' => '1962-07-12', 'sex' => 'M', 'marital_status' => 'Separated', 'address' => 'Lapasan, Cagayan de Oro',                   'phone_number' => '09251000079', 'date_registered' => '2025-08-20'],
            ['first_name' => 'Herminia',     'last_name' => 'Llamas',       'date_of_birth' => '1941-03-25', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Gusa, Cagayan de Oro',                      'phone_number' => '09261000080', 'date_registered' => '2025-08-22'],
            ['first_name' => 'Quintin',      'last_name' => 'Maceda',       'date_of_birth' => '1957-12-08', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Nazareth, Cagayan de Oro',                  'phone_number' => '09271000081', 'date_registered' => '2025-09-01'],
            ['first_name' => 'Gregoria',     'last_name' => 'Narciso',      'date_of_birth' => '1939-08-21', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Camaman-an, Cagayan de Oro',                'phone_number' => '09281000082', 'date_registered' => '2025-09-03'],
            ['first_name' => 'Leoncio',      'last_name' => 'Ochoa',        'date_of_birth' => '1953-05-04', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Carmen, Cagayan de Oro',                    'phone_number' => '09291000083', 'date_registered' => '2025-09-05'],
            ['first_name' => 'Norma',        'last_name' => 'Pelayo',       'date_of_birth' => '1946-01-17', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Macabalan, Cagayan de Oro',                 'phone_number' => '09301000084', 'date_registered' => '2025-09-08'],
            ['first_name' => 'Emiliano',     'last_name' => 'Quezon',       'date_of_birth' => '1967-10-30', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Indahag, Cagayan de Oro',                   'phone_number' => '09171000085', 'date_registered' => '2025-09-10'],
            ['first_name' => 'Dalisay',      'last_name' => 'Regalado',     'date_of_birth' => '1943-07-13', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Cugman, Cagayan de Oro',                    'phone_number' => '09181000086', 'date_registered' => '2025-09-12'],
            ['first_name' => 'Celestino',    'last_name' => 'Salcedo',      'date_of_birth' => '1951-03-26', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Balulang, Cagayan de Oro',                  'phone_number' => '09191000087', 'date_registered' => '2025-09-15'],
            ['first_name' => 'Concepcion',   'last_name' => 'Tanedo',       'date_of_birth' => '1937-12-09', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Iponan, Cagayan de Oro',                    'phone_number' => '09201000088', 'date_registered' => '2025-09-18'],
            ['first_name' => 'Domingo',      'last_name' => 'Ubaldo',       'date_of_birth' => '1960-08-22', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Agusan, Cagayan de Oro',                    'phone_number' => '09211000089', 'date_registered' => '2025-09-20'],
            ['first_name' => 'Nieves',       'last_name' => 'Varona',       'date_of_birth' => '1945-05-05', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Consolacion, Cagayan de Oro',               'phone_number' => '09221000090', 'date_registered' => '2025-09-22'],
            ['first_name' => 'Apolinario',   'last_name' => 'Waga',         'date_of_birth' => '1955-01-18', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Puerto, Cagayan de Oro',                    'phone_number' => '09231000091', 'date_registered' => '2025-10-01'],
            ['first_name' => 'Margarita',    'last_name' => 'Ybanez',       'date_of_birth' => '1940-10-01', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Kauswagan, Cagayan de Oro',                 'phone_number' => '09241000092', 'date_registered' => '2025-10-03'],
            ['first_name' => 'Filomeno',     'last_name' => 'Zabala',       'date_of_birth' => '1964-06-14', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Barangay 4, Cagayan de Oro',                'phone_number' => '09251000093', 'date_registered' => '2025-10-05'],
            ['first_name' => 'Resureccion',  'last_name' => 'Abella',       'date_of_birth' => '1942-02-27', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Lapasan, Cagayan de Oro',                   'phone_number' => '09261000094', 'date_registered' => '2025-10-08'],
            ['first_name' => 'Bibiano',      'last_name' => 'Boquiren',     'date_of_birth' => '1949-11-10', 'sex' => 'M', 'marital_status' => 'Separated', 'address' => 'Gusa, Cagayan de Oro',                      'phone_number' => '09271000095', 'date_registered' => '2025-10-10'],
            ['first_name' => 'Nena',         'last_name' => 'Cainglet',     'date_of_birth' => '1935-07-23', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Nazareth, Cagayan de Oro',                  'phone_number' => '09281000096', 'date_registered' => '2025-10-12'],
            ['first_name' => 'Rodolfo',      'last_name' => 'Dacanay',      'date_of_birth' => '1968-04-06', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Camaman-an, Cagayan de Oro',                'phone_number' => '09291000097', 'date_registered' => '2025-10-15'],
            ['first_name' => 'Lourdes',      'last_name' => 'Empleo',       'date_of_birth' => '1944-12-19', 'sex' => 'F', 'marital_status' => 'Married',   'address' => 'Carmen, Cagayan de Oro',                    'phone_number' => '09301000098', 'date_registered' => '2025-10-18'],
            ['first_name' => 'Segundo',      'last_name' => 'Fontanilla',   'date_of_birth' => '1952-09-02', 'sex' => 'M', 'marital_status' => 'Married',   'address' => 'Macabalan, Cagayan de Oro',                 'phone_number' => '09171000099', 'date_registered' => '2025-10-20'],
            ['first_name' => 'Pilar',        'last_name' => 'Guzman',       'date_of_birth' => '1941-05-15', 'sex' => 'F', 'marital_status' => 'Widowed',   'address' => 'Indahag, Cagayan de Oro',                   'phone_number' => '09181000100', 'date_registered' => '2025-10-22'],
        ];

        foreach ($patients as $patient) {
            DB::table('patients')->insert([
                ...$patient,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('100 patients seeded successfully.');
    }
}
